#!/usr/bin/env bash

declare -x VULCAND_LOG_SEVERITY
[[ -z "${VULCAND_LOG_SEVERITY}" ]] && VULCAND_LOG_SEVERITY="warning"

declare -x VULCAND_ALIASES
[[ -z "${VULCAND_ALIASES}" ]] && VULCAND_ALIASES=""

declare -x VULCAND_CERTPATH
[[ -z "${VULCAND_CERTPATH}" ]] && VULCAND_CERTPATH=""

declare -x VULCAND_DEBUG_JAEGER_TRACING
[[ -z "${VULCAND_DEBUG_JAEGER_TRACING}" ]] && VULCAND_DEBUG_JAEGER_TRACING="false"

declare -x VULCAND_DEFAULT_LISTENER
[[ -z "${VULCAND_DEFAULT_LISTENER}" ]] && VULCAND_DEFAULT_LISTENER="true"

declare -x VULCAND_ENABLE_JAEGER_TRACING
[[ -z "${VULCAND_ENABLE_JAEGER_TRACING}" ]] && VULCAND_ENABLE_JAEGER_TRACING="false"

declare -x VULCAND_ENDPOINT_DIAL_TIMEOUT
[[ -z "${VULCAND_ENDPOINT_DIAL_TIMEOUT}" ]] && VULCAND_ENDPOINT_DIAL_TIMEOUT=""

declare -x VULCAND_ENDPOINT_READ_TIMEOUT
[[ -z "${VULCAND_ENDPOINT_READ_TIMEOUT}" ]] && VULCAND_ENDPOINT_READ_TIMEOUT=""

declare -x VULCAND_ENGINE
[[ -z "${VULCAND_ENGINE}" ]] && VULCAND_ENGINE="etcd"

declare -x VULCAND_MEM_PROFILE_RATE
[[ -z "${VULCAND_MEM_PROFILE_RATE}" ]] && VULCAND_MEM_PROFILE_RATE=""

declare -x VULCAND_SEAL_KEY
[[ -z "${VULCAND_SEAL_KEY}" ]] && VULCAND_SEAL_KEY=""

declare -x VULCAND_SERVER_MAX_HEADER_BYTES
[[ -z "${VULCAND_SERVER_MAX_HEADER_BYTES}" ]] && VULCAND_SERVER_MAX_HEADER_BYTES=""

declare -x VULCAND_SERVER_READ_TIMEOUT
[[ -z "${VULCAND_SERVER_READ_TIMEOUT}" ]] && VULCAND_SERVER_READ_TIMEOUT=""

declare -x VULCAND_SERVER_WRITE_TIMEOUT
[[ -z "${VULCAND_SERVER_WRITE_TIMEOUT}" ]] && VULCAND_SERVER_WRITE_TIMEOUT=""

declare -x VULCAND_STATSD_ADDR
[[ -z "${VULCAND_STATSD_ADDR}" ]] && VULCAND_STATSD_ADDR=""

declare -x VULCAND_STATSD_PREFIX
[[ -z "${VULCAND_STATSD_PREFIX}" ]] && VULCAND_STATSD_PREFIX=""

declare -x VULCAND_TRUST_FORWARD_HEADER
[[ -z "${VULCAND_TRUST_FORWARD_HEADER}" ]] && VULCAND_TRUST_FORWARD_HEADER="false"

declare -x VULCAND_ETCD
[[ -z "${VULCAND_ETCD}" ]] && VULCAND_ETCD="http://etcd:2379"

declare -x VULCAND_ETCD_API_VERSION
[[ -z "${VULCAND_ETCD_API_VERSION}" ]] && VULCAND_ETCD_API_VERSION="3"

declare -x VULCAND_ETCD_KEY
[[ -z "${VULCAND_ETCD_KEY}" ]] && VULCAND_ETCD_KEY="vulcand"

declare -x VULCAND_ETCD_SYNC_INTERVAL_SECONDS
[[ -z "${VULCAND_ETCD_SYNC_INTERVAL_SECONDS}" ]] && VULCAND_ETCD_SYNC_INTERVAL_SECONDS=""

declare -x VULCAND_ETCD_CONSISTENCY
[[ -z "${VULCAND_ETCD_CONSISTENCY}" ]] && VULCAND_ETCD_CONSISTENCY="STRONG"

declare -x VULCAND_ETCD_ENABLE_TLS
[[ -z "${VULCAND_ETCD_ENABLE_TLS}" ]] && VULCAND_ETCD_ENABLE_TLS="false"

declare -x VULCAND_ETCD_CA_FILE
[[ -z "${VULCAND_ETCD_CA_FILE}" ]] && VULCAND_ETCD_CA_FILE=""

declare -x VULCAND_ETCD_CERT_FILE
[[ -z "${VULCAND_ETCD_CERT_FILE}" ]] && VULCAND_ETCD_CERT_FILE=""

declare -x VULCAND_ETCD_KEY_FILE
[[ -z "${VULCAND_ETCD_KEY_FILE}" ]] && VULCAND_ETCD_KEY_FILE=""

declare -x VULCAND_ETCD_INSECURE_SKIP_VERIFY
[[ -z "${VULCAND_ETCD_INSECURE_SKIP_VERIFY}" ]] && VULCAND_ETCD_INSECURE_SKIP_VERIFY="false"

declare -x VULCAND_ETCD_USERNAME
[[ -z "${VULCAND_ETCD_USERNAME}" ]] && VULCAND_ETCD_USERNAME=""

declare -x VULCAND_ETCD_PASSWORD
[[ -z "${VULCAND_ETCD_PASSWORD}" ]] && VULCAND_ETCD_PASSWORD=""

declare -x VULCAND_ETCD_DEBUG
[[ -z "${VULCAND_ETCD_DEBUG}" ]] && VULCAND_ETCD_DEBUG="false"

declare -x VULCAND_HEALTHCHECK_URL
[[ -z "${VULCAND_HEALTHCHECK_URL}" ]] && VULCAND_HEALTHCHECK_URL="http://localhost:8182/v2/status"

declare -x VULCAND_HEALTHCHECK_CODE
[[ -z "${VULCAND_HEALTHCHECK_CODE}" ]] && VULCAND_HEALTHCHECK_CODE="200"

declare -x ETCDCTL_COMMAND
[[ -z "${ETCDCTL_COMMAND}" ]] && ETCDCTL_COMMAND="etcdctl --endpoints=${VULCAND_ETCD}"

true
