FROM ghcr.io/dockhippie/golang:1.23-amd64@sha256:f1ee285b07d72095b9470e2491205ba5199b06a820576c7a593dd31965f8f314 AS build

RUN git clone -b master https://github.com/vulcand/vulcand.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install ./...

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:d272886ae1ebdd406578fd5bb3b050e770a529f33c98ba20bf5f664118fe352f

EXPOSE 8181 8182

WORKDIR /var/lib/vulcand
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add etcd-ctl@testing && \
  mkdir -p /var/lib/vulcand && \
  groupadd -g 1000 vulcand && \
  useradd -u 1000 -d /var/lib/vulcand -g vulcand -s /bin/bash -M vulcand && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/vulcand /usr/bin/vulcand
COPY --from=build /srv/app/bin/vctl /usr/bin/vctl
COPY --from=build /srv/app/bin/vbundle /usr/bin/vbundle
COPY ./overlay /
