FROM ghcr.io/dockhippie/golang:1.23-amd64@sha256:c5e6f7ed526f0f4a893dc465369b2ea5da2a424bdbc77a7aa7ee2f440d2a3e83 AS build

RUN git clone -b master https://github.com/vulcand/vulcand.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install ./...

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:a109ce2151f8811f7dfcf8ed3a7437c792897f5455c2689ceea4e5db694faccf

EXPOSE 8181 8182

WORKDIR /var/lib/vulcand
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add etcd-ctl@testing && \
  mkdir -p /var/lib/vulcand && \
  groupadd -g 1000 vulcand && \
  useradd -u 1000 -d /var/lib/vulcand -g vulcand -s /bin/bash -M vulcand && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/vulcand /usr/bin/vulcand
COPY --from=build /srv/app/bin/vctl /usr/bin/vctl
COPY --from=build /srv/app/bin/vbundle /usr/bin/vbundle
COPY ./overlay /
