FROM ghcr.io/dockhippie/golang:1.25-amd64@sha256:4576975589ecad361f7848c93aa0989d9f305135f04c940614c9004228db5e81 AS build

RUN git clone -b master https://github.com/vulcand/vulcand.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install ./...

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:e9853aa23cf4ad58e922decc6268a4e3a5626f2f973ef876550c9c27e9fd077c

EXPOSE 8181 8182

WORKDIR /var/lib/vulcand
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add etcd-ctl@testing && \
  mkdir -p /var/lib/vulcand && \
  groupadd -g 1000 vulcand && \
  useradd -u 1000 -d /var/lib/vulcand -g vulcand -s /bin/bash -M vulcand && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/vulcand /usr/bin/vulcand
COPY --from=build /srv/app/bin/vctl /usr/bin/vctl
COPY --from=build /srv/app/bin/vbundle /usr/bin/vbundle
COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/healthcheck /usr/bin/container && \
  chmod +x /usr/bin/healthcheck /usr/bin/container /etc/container.d/*.sh /etc/entrypoint.d/*.sh
