FROM ghcr.io/dockhippie/golang:1.23-arm64@sha256:665ff51cc67c66cb6c257e7b5ea88a02a2a344eeec0e726bafb729d306fe9bad AS build

# renovate: datasource=github-tags depName=vulcand/vulcand
ENV VULCAND_VERSION=v0.9.2

RUN git clone -b ${VULCAND_VERSION} https://github.com/vulcand/vulcand.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install ./...

FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:1312caff163a115533faae61a58ef9118c9f813d3ccc1ff4d0ef07ba1583d986

EXPOSE 8181 8182

WORKDIR /var/lib/vulcand
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add etcd-ctl@testing && \
  mkdir -p /var/lib/vulcand && \
  groupadd -g 1000 vulcand && \
  useradd -u 1000 -d /var/lib/vulcand -g vulcand -s /bin/bash -M vulcand && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/vulcand /usr/bin/vulcand
COPY --from=build /srv/app/bin/vctl /usr/bin/vctl
COPY --from=build /srv/app/bin/vbundle /usr/bin/vbundle
COPY ./overlay /
