FROM ghcr.io/dockhippie/golang:1.23-amd64@sha256:f7deb84f961ad03529858ae3211c64808e2da24c5911b5926ff1856ee22c7cca AS build

# renovate: datasource=github-tags depName=vulcand/vulcand
ENV VULCAND_VERSION=v0.9.2

RUN git clone -b ${VULCAND_VERSION} https://github.com/vulcand/vulcand.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install ./...

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:f8ecf52e2134f9692a269f79c43fc96c9bdc475849bcfcda0ac1a5a9c2602177

EXPOSE 8181 8182

WORKDIR /var/lib/vulcand
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add etcd-ctl@testing && \
  mkdir -p /var/lib/vulcand && \
  groupadd -g 1000 vulcand && \
  useradd -u 1000 -d /var/lib/vulcand -g vulcand -s /bin/bash -M vulcand && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/vulcand /usr/bin/vulcand
COPY --from=build /srv/app/bin/vctl /usr/bin/vctl
COPY --from=build /srv/app/bin/vbundle /usr/bin/vbundle
COPY ./overlay /
