FROM ghcr.io/dockhippie/golang:1.25-amd64@sha256:f25e3806e58ff056471ad435e6d46f7ad99f0c7af48716834f62930dcf6eb5ac AS build

# renovate: datasource=github-tags depName=vulcand/vulcand
ENV VULCAND_VERSION=v0.9.2

RUN git clone -b ${VULCAND_VERSION} https://github.com/vulcand/vulcand.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install ./...

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:f2a9d34a6b2c077d31fc74f1fbbe34481ae06cabd73564890c83df1b9f7edcbf

EXPOSE 8181 8182

WORKDIR /var/lib/vulcand
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add etcd-ctl@testing && \
  mkdir -p /var/lib/vulcand && \
  groupadd -g 1000 vulcand && \
  useradd -u 1000 -d /var/lib/vulcand -g vulcand -s /bin/bash -M vulcand && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/vulcand /usr/bin/vulcand
COPY --from=build /srv/app/bin/vctl /usr/bin/vctl
COPY --from=build /srv/app/bin/vbundle /usr/bin/vbundle
COPY ./overlay /
