FROM ghcr.io/dockhippie/golang:1.23-arm64@sha256:adc258633a29abf8b83336173e21b8fd20b3c2692d584f289235a08a7565a054 AS build

# renovate: datasource=github-tags depName=vulcand/vulcand
ENV VULCAND_VERSION=v0.9.2

RUN git clone -b ${VULCAND_VERSION} https://github.com/vulcand/vulcand.git /srv/app/src && \
  cd /srv/app/src && \
  GO111MODULE=on go install ./...

FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:5a0bc04409259a9a210a5bcac2beda4691ceac7ab1ad1da0b34596dca7ff2ca3

EXPOSE 8181 8182

WORKDIR /var/lib/vulcand
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add etcd-ctl@testing && \
  mkdir -p /var/lib/vulcand && \
  groupadd -g 1000 vulcand && \
  useradd -u 1000 -d /var/lib/vulcand -g vulcand -s /bin/bash -M vulcand && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/vulcand /usr/bin/vulcand
COPY --from=build /srv/app/bin/vctl /usr/bin/vctl
COPY --from=build /srv/app/bin/vbundle /usr/bin/vbundle
COPY ./overlay /
