#!/usr/bin/env bash
# Usage: manage start
# Summary: Start the main process
# Help: This command is used to start the main process.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

if manage-running
then
  echo "Service is already running"
else
  trap "manage-stop" SIGTERM
  STARTCMD="/usr/bin/vulcand -port=8181 -apiPort=8182"

  if [ -n "${VULCAND_API_INTERFACE}" ]
  then
    STARTCMD="${STARTCMD} -apiInterface=${VULCAND_API_INTERFACE}"
  fi

  if [ -n "${VULCAND_ENDPOINT_DIALTIMEOUT}" ]
  then
    STARTCMD="${STARTCMD} -endpointDialTimeout=${VULCAND_ENDPOINT_DIALTIMEOUT}"
  fi

  if [ -n "${VULCAND_ENDPOINT_READTIMEOUT}" ]
  then
    STARTCMD="${STARTCMD} -endpointReadTimeout=${VULCAND_ENDPOINT_READTIMEOUT}"
  fi

  if [ -n "${VULCAND_ETCD}" ]
  then
    STARTCMD="${STARTCMD} -etcd=${VULCAND_ETCD}"
  fi

  if [ -n "${VULCAND_ETCD_CONSISTENCY}" ]
  then
    STARTCMD="${STARTCMD} -etcdConsistency=${VULCAND_ETCD_CONSISTENCY}"
  fi

  if [ -n "${VULCAND_ETCD_KEY}" ]
  then
    STARTCMD="${STARTCMD} -etcdKey=${VULCAND_ETCD_KEY}"
  fi

  if [ -n "${VULCAND_INTERFACE}" ]
  then
    STARTCMD="${STARTCMD} -interface=${VULCAND_INTERFACE}"
  fi

  if [ -n "${VULCAND_LOG}" ]
  then
    STARTCMD="${STARTCMD} -log=${VULCAND_LOG}"
  fi

  if [ -n "${VULCAND_LOG_SEVERITY}" ]
  then
    STARTCMD="${STARTCMD} -logSeverity=${VULCAND_LOG_SEVERITY}"
  fi

  if [ -n "${VULCAND_READTIMEOUT}" ]
  then
    STARTCMD="${STARTCMD} -readTimeout=${VULCAND_READTIMEOUT}"
  fi

  if [ -n "${VULCAND_SEALKEY}" ]
  then
    STARTCMD="${STARTCMD} -sealKey=${VULCAND_SEALKEY}"
  fi

  if [ -n "${VULCAND_SERVER_MAXHEADERBYTES}" ]
  then
    STARTCMD="${STARTCMD} -serverMaxHeaderBytes=${VULCAND_SERVER_MAXHEADERBYTES}"
  fi

  if [ -n "${VULCAND_SERVER_READTIMEOUT}" ]
  then
    STARTCMD="${STARTCMD} -serverReadTimeout=${VULCAND_SERVER_READTIMEOUT}"
  fi

  if [ -n "${VULCAND_SERVER_WRITETIMEOUT}" ]
  then
    STARTCMD="${STARTCMD} -serverWriteTimeout=${VULCAND_SERVER_WRITETIMEOUT}"
  fi

  if [ -n "${VULCAND_STATSD_ADDR}" ]
  then
    STARTCMD="${STARTCMD} -statsdAddr=${VULCAND_STATSD_ADDR}"
  fi

  if [ -n "${VULCAND_STATSD_PREFIX}" ]
  then
    STARTCMD="${STARTCMD} -statsdPrefix=${VULCAND_STATSD_PREFIX}"
  fi

  if [ -n "${VULCAND_CERTPATH}" ]
  then
    if [ -f "${VULCAND_CERTPATH}" ]
    then
      STARTCMD="${STARTCMD} -certPath=${VULCAND_CERTPATH}"
    else
      echo -e "${VULCAND_CERTPATH}" >| /tmp/vulcand.crt
      STARTCMD="${STARTCMD} -certPath=/tmp/vulcand.crt"
    fi
  fi

  if [ -n "${VULCAND_ETCD_CAFILE}" ]
  then
    if [ -f "${VULCAND_ETCD_CAFILE}" ]
    then
      STARTCMD="${STARTCMD} -etcdCaFile=${VULCAND_ETCD_CAFILE}"
    else
      echo -e "${VULCAND_ETCD_CAFILE}" >| /tmp/ca.crt
      STARTCMD="${STARTCMD} -etcdCaFile=/tmp/ca.crt"
    fi
  fi

  if [ -n "${VULCAND_ETCD_CERTFILE}" ]
  then
    if [ -f "${VULCAND_ETCD_CERTFILE}" ]
    then
      STARTCMD="${STARTCMD} -etcdCertFile=${VULCAND_ETCD_CERTFILE}"
    else
      echo -e "${VULCAND_ETCD_CERTFILE}" >| /tmp/etcd.crt
      STARTCMD="${STARTCMD} -etcdCertFile=/tmp/etcd.crt"
    fi
  fi

  if [ -n "${VULCAND_ETCD_KEYFILE}" ]
  then
    if [ -f "${VULCAND_ETCD_KEYFILE}" ]
    then
      STARTCMD="${STARTCMD} -etcdKeyFile=${VULCAND_ETCD_KEYFILE}"
    else
      echo -e "${VULCAND_ETCD_KEYFILE}" >| /tmp/etcd.key
      STARTCMD="${STARTCMD} -etcdKeyFile=/tmp/etcd.key"
    fi
  fi

  ${STARTCMD}
fi
