#!/usr/bin/env bash
# Usage: manage pid
# Summary: Return the process id
# Help: This command is used to gather the process id of the main process.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

pgrep -f vulcand
