#!/usr/bin/env bash
# Usage: manage stop
# Summary: Stop the main process
# Help: This command is used to stop the main process.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

if manage-running
then
  kill -INT $(manage-pid)
else
  echo "Service is not running"
fi
